[pytest]
# 1. on part de la racine
pythonpath = src/app_api src/app_front src/app_train
# 1. Où sont tes tests ?
testpaths = tests

# 2. Quelles sont les options par défaut ?
# -v : Verbeux
# --cov : Lance le coverage sur ton dossier de code (ici la racine .)
# --cov-report : Affiche le résumé dans le terminal et crée un dossier html
addopts = -v --cov=. --cov-report=term-missing --cov-report=html

# 3. Quels fichiers scanner ?
python_files = test_*.py

# 4. Ignorer certains dossiers (pour aller plus vite)
norecursedirs = docs public .venv .git